#	Generate Tab5/font.h — three monospace bitmap fonts with SliP's alphabet.
#
#		python3 Tab5/font.py            # run from the repository root
#
#	The same job as RP2350/font.py and the same reasoning: no font on the board,
#	no font file to load, and no stock ROM font that has π ∅ ∥ ⟨ ⟩ 𝑒 in it — those
#	are the language.  No single face on a Mac has all of it either, so the glyphs
#	are rendered one at a time against a chain and the first face that has the
#	character wins.  𝑒 (U+1D452, Mathematical Alphanumeric Symbols) is in neither
#	Menlo nor Apple Symbols; STIX Two Math is the one that matches.
#
#	What is different here is that there are three of them.  The panel has three
#	keypads — a calculator, a scientific calculator, and the whole language — and
#	each fits a different number of keys across 720 pixels, so each wants its own
#	size rather than a scaled copy of one.  Scaling a bitmap font by 1.5 is how
#	you get a font that looks like a scaled bitmap font.
#
#	The alphabet also grew.  The RP2350's pad had no letters at all, so a session
#	there could use the two names M1 and M2 and no others.  There is room here for
#	the Greek lowercase, which the reader has always accepted as names — so this
#	is the first host where a name can be made up on the panel.
#
#	Needs Pillow and fontTools.

from PIL import Image, ImageDraw, ImageFont
from fontTools.ttLib import TTFont, TTCollection

OUT = "Tab5/main/font.h"

#	( name, cell width, cell height, point size )
SIZES = (
	( "L", 24, 48, 40 ),		#	the calculator: few keys, large
	( "M", 18, 36, 30 ),		#	scientific: the functions as well
	( "S", 12, 24, 20 ),		#	the language: every operator
)

MONO  = "/System/Library/Fonts/Menlo.ttc"
SYM   = "/System/Library/Fonts/Apple Symbols.ttf"
MATH  = "/System/Library/Fonts/Supplemental/STIXTwoMath.otf"		#	the only face here with 𝑒
CHAIN = ( MONO, SYM, MATH )

#	ASCII, then the operators the reader knows, then the Greek the reader takes
#	as names — both cases, as Read.cpp lists them.
CHARS = (
	[ chr( c ) for c in range( 0x20, 0x7F ) ]
+	list( "×÷±·∈∋¿¬¡¦§∥⟨⟩«»𝑒π£¶¤∅∞⊤⊥≠≤≥‹›⊂⊃∩∪" )
+	list( "ΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩ" )
+	list( "αβγδεζηθικλμνξοπρστυφχψως" )
+	list( "⌫␣⏎↵—√▶▼…" )
)
CHARS = list( dict.fromkeys( CHARS ) )			#	π appears twice; keep the first

_cmaps = {}
def cmap( path ):
	if path not in _cmaps:
		f = TTCollection( path ).fonts[ 0 ] if path.endswith( ".ttc" ) else TTFont( path )
		s = set()
		for t in f[ "cmap" ].tables: s |= set( t.cmap.keys() )
		_cmaps[ path ] = s
	return _cmaps[ path ]

def face( ch, size ):
	for p in CHAIN:
		if ord( ch ) in cmap( p ): return ImageFont.truetype( p, size )
	return None

#	One baseline for every glyph in a size, taken from the primary face.  Centring
#	each glyph's ink box in its cell instead — which RP2350/font.py did at first —
#	puts every character on a line of its own: the full stop floats to the middle
#	of the row and the quote sinks.  Only the horizontal centring is per glyph,
#	because the fallback faces are not monospace.
def bitmaps( W, H, SIZE ):
	ascent, descent = ImageFont.truetype( MONO, SIZE ).getmetrics()
	baseline = ( H + ascent - descent ) // 2

	rows_of, missing = [], []
	for ch in CHARS:
		f = face( ch, SIZE )
		if f is None:
			rows_of.append( [ 0 ] * H )
			if ch != " ": missing.append( ch )
			continue
		im = Image.new( "L", ( W, H ), 0 )
		d  = ImageDraw.Draw( im )
		box = d.textbbox( ( 0, baseline ), ch, font = f, anchor = "ls" )
		x   = ( W - ( box[ 2 ] - box[ 0 ] ) ) / 2 - box[ 0 ]
		d.text( ( x, baseline ), ch, font = f, fill = 255, anchor = "ls" )

		px, rows = im.load(), []
		for r in range( H ):
			bits = 0
			for c in range( W ):
				if px[ c, r ] >= 96: bits |= 1 << ( W - 1 - c )
			rows.append( bits )
		if not any( rows ) and ch != " ": missing.append( ch )
		rows_of.append( rows )
	return rows_of, missing

def main():
	order = sorted( range( len( CHARS ) ), key = lambda i: ord( CHARS[ i ] ) )

	out = [
		"//\tGenerated by Tab5/font.py — do not edit.",
		"//",
		f"//\t{len(CHARS)} glyphs in three sizes, one uint32_t per row.",
		"//\tThe codepoints are sorted, so a lookup is a binary search.",
		"",
		"#pragma once",
		"#include <cstdint>",
		"",
		f"static constexpr int FONT_N = {len(CHARS)};",
		"",
		"static const uint32_t FONT_CODEPOINT[ FONT_N ] = {",
		"\t" + ", ".join( str( ord( CHARS[ i ] ) ) for i in order ),
		"};",
		"",
	]

	for name, W, H, SIZE in SIZES:
		rows_of, missing = bitmaps( W, H, SIZE )
		out += [
			f"static constexpr int FONT_{name}_W = {W};",
			f"static constexpr int FONT_{name}_H = {H};",
			f"static const uint32_t FONT_{name}_BITS[ FONT_N ][ FONT_{name}_H ] = {{",
		]
		for i in order:
			out.append(
				"\t{ " + ", ".join( f"0x{r:06X}" for r in rows_of[ i ] )
			+	" },  //  U+%04X" % ord( CHARS[ i ] )
			)
		out += [ "};", "" ]
		print( f"  {name}: {W}x{H} at {SIZE}pt, {len(rows_of)*H*4} bytes"
		     + ( "   no glyph for: " + "".join( missing ) if missing else "" ) )

	open( OUT, "w" ).write( "\n".join( out ) )
	print( f"{OUT}: {len(CHARS)} glyphs" )

main()
