#	Generate RP2350/font.h — a monospace bitmap font with SliP's alphabet in it.
#
#		python3 RP2350/font.py          # run from the repository root
#
#	No font on the board, and no font file to load: the glyphs are baked into
#	flash as a bitmap.  What has to be in there is ASCII plus the operators, which
#	is the whole reason this is generated rather than borrowed — π ∅ ∥ ⟨ ⟩ 𝑒 are
#	the language, and a stock 8x16 ROM font has none of them.
#
#	No single face covers it either.  Menlo has all of ASCII and most of the
#	operators; Apple Symbols has nearly all the rest; and 𝑒 — U+1D452, in the
#	Mathematical Alphanumeric Symbols block — is in neither, which is worth
#	knowing because it is a constant of the language and a key on the pad.  Of
#	everything installed on this Mac, four faces have it and STIX Two Math is the
#	one that matches.  Glyphs are rendered one at a time against that chain, first
#	face that has the character wins, and each is centred in a fixed cell the way
#	a terminal would.
#
#	Needs Pillow and fontTools.

from PIL import Image, ImageDraw, ImageFont
from fontTools.ttLib import TTFont, TTCollection

W, H  = 12, 24			#	cell; 240 / 12 = 20 columns
SIZE  = 20				#	point size that fills that cell without touching it
OUT   = "RP2350/font.h"

MONO  = "/System/Library/Fonts/Menlo.ttc"
SYM   = "/System/Library/Fonts/Apple Symbols.ttf"
MATH  = "/System/Library/Fonts/Supplemental/STIXTwoMath.otf"		#	the only face here with 𝑒, U+1D452
CHAIN = ( MONO, SYM, MATH )

#	ASCII, then everything SliP writes that is not in it.
CHARS = [ chr( c ) for c in range( 0x20, 0x7F ) ] + list(
	"×÷±·∈∋¿¬¡¦§∥⟨⟩«»𝑒π£¶¤∅∞⊤⊥≠≤≥θγφ‹›⌫␣⏎↵—"
)

_cmaps = {}
def cmap( path ):
	if path not in _cmaps:
		f = TTCollection( path ).fonts[ 0 ] if path.endswith( ".ttc" ) else TTFont( path )
		s = set()
		for t in f[ "cmap" ].tables: s |= set( t.cmap.keys() )
		_cmaps[ path ] = s
	return _cmaps[ path ]

def face( ch ):
	for p in CHAIN:
		if ord( ch ) in cmap( p ): return ImageFont.truetype( p, SIZE )
	return None

#	One baseline for every glyph, taken from the primary face.  Centring each
#	glyph's ink box in its cell instead — which is what this did at first — puts
#	every character on a line of its own: the full stop floats to the middle of
#	the row, the quote sinks, and digits shift by whether they have a descender.
#	Only the horizontal centring is per glyph, because the fallback faces are not
#	monospace and a left-aligned ∥ beside a left-aligned M reads as a mistake.
BASELINE = None

def bitmap( ch ):
	global BASELINE
	f = face( ch )
	if f is None: return [ 0 ] * H, False
	im = Image.new( "L", ( W, H ), 0 )
	d  = ImageDraw.Draw( im )
	if BASELINE is None:
		ascent, descent = ImageFont.truetype( MONO, SIZE ).getmetrics()
		BASELINE = ( H + ascent - descent ) // 2
	box = d.textbbox( ( 0, BASELINE ), ch, font = f, anchor = "ls" )
	x   = ( W - ( box[ 2 ] - box[ 0 ] ) ) / 2 - ( box[ 0 ] - 0 )
	d.text( ( x, BASELINE ), ch, font = f, fill = 255, anchor = "ls" )

	rows = []
	px   = im.load()
	for r in range( H ):
		bits = 0
		for c in range( W ):
			if px[ c, r ] >= 96: bits |= 1 << ( W - 1 - c )
		rows.append( bits )
	return rows, any( rows )

def main():
	glyphs, index, missing = [], [], []
	for ch in CHARS:
		rows, ok = bitmap( ch )
		if not ok and ch != " ": missing.append( ch )
		index.append( ( ord( ch ), len( glyphs ) ) )
		glyphs.append( rows )

	out = [
		"//\tGenerated by RP2350/font.py — do not edit.",
		"//",
		f"//\t{len(glyphs)} glyphs, {W}x{H} in a cell, one uint16_t per row.",
		"//\tThe codepoints are sorted, so a lookup is a binary search.",
		"",
		"#pragma once",
		"#include <cstdint>",
		"",
		f"static constexpr int FONT_W = {W};",
		f"static constexpr int FONT_H = {H};",
		f"static constexpr int FONT_N = {len(glyphs)};",
		"",
		"static const uint32_t FONT_CODEPOINT[ FONT_N ] = {",
	]
	order = sorted( range( len( index ) ), key = lambda i: index[ i ][ 0 ] )
	out.append( "\t" + ", ".join( str( index[ i ][ 0 ] ) for i in order ) )
	out += [ "};", "", "static const uint16_t FONT_BITS[ FONT_N ][ FONT_H ] = {" ]
	for i in order:
		rows = glyphs[ index[ i ][ 1 ] ]
		out.append( "\t{ " + ", ".join( f"0x{r:04X}" for r in rows ) + " },  //  U+%04X" % index[ i ][ 0 ] )
	out += [ "};", "" ]

	open( OUT, "w" ).write( "\n".join( out ) )
	print( f"{OUT}: {len(glyphs)} glyphs, {len(glyphs)*H*2} bytes of bitmap" )
	if missing: print( "  no glyph for:", "".join( missing ) )

main()
